"""003_add_verification_strategy_to_gyms

Revision ID: 003
Revises: 002
Create Date: 2025-10-07 22:36:39.844340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '003'
down_revision: Union[str, Sequence[str], None] = '002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type first
    verification_strategy_enum = sa.Enum('VERIFICATION_ENDPOINT', 'RUN_ID_ASSERTIONS', 'LOCAL_STORAGE_ASSERTIONS', name='verificationstrategy')
    verification_strategy_enum.create(op.get_bind())
    
    # Add the new column with default value
    op.add_column('gyms', sa.Column('verification_strategy', verification_strategy_enum, nullable=False, server_default='VERIFICATION_ENDPOINT'))
    
    # Drop the old column
    op.drop_column('gyms', 'verification_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add back the verification_url column
    op.add_column('gyms', sa.Column('verification_url', sa.TEXT(), autoincrement=False, nullable=True))
    
    # Drop the verification_strategy column
    op.drop_column('gyms', 'verification_strategy')
    
    # Drop the enum type
    verification_strategy_enum = sa.Enum('VERIFICATION_ENDPOINT', 'RUN_ID_ASSERTIONS', 'LOCAL_STORAGE_ASSERTIONS', name='verificationstrategy')
    verification_strategy_enum.drop(op.get_bind())
    # ### end Alembic commands ###
